name: pipeline
on:
  push:
    branches:
      - 'main'
      - 'dev'

permissions:
  contents: read

jobs:
  build: # Name of first job.
    runs-on: ubuntu-latest # Defines the runner that will run the job.
    timeout-minutes: 5
    steps: # Steps in the job
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - uses: actions/checkout@v3
#      - name: Caching dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-
      - name: Install package & dependencies
        run: |
          echo "Installing chemtools"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chemtools_artifact
          path: .
  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: flake8
        run: |
            pip install -e .
            flake8 . --show-source --statistics -v
      - name: mypy
        run: |
          mypy chemlearn
#      - name: pytest
#        run: |
#          pytest -v